### PR TITLE
feat: addToCalendar function

### PR DESCRIPTION
**Pull request by chadoh**
I needed the ability to use the wonderful "add to calendar" _action_
without using the same HTML-based setup & initialization.

This renames `atcb_open` to `atcb_addToCalendar` and reworks it to
generate the dropdown list and background overlay _only when clicked_.
This has no discernible performance impact, while making it possible to
also use the function directly, without needing `atcb_init`.

In the NPM package, the prefix is removed, so that NPM users can:

    import { addToCalendar } from 'add-to-calendar-button'

This also positions the dropdown list below the relevant button using
absolute positioning while putting it elsewhere in the DOM. This
required some CSS tweaks. It will also help avoid z-index styling
issues, which can be a problem when putting dropdowns directly adjacent
to the trigger within the DOM.

If someone calls `addToCalendar` without specifying a second argument,
the dropdown list is shown as a modal.

Finally, the new format required getting rid of the implicit `this`
binding. Instead, arrow functions have been used throughout.

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

-   [x] My code follows the code style of this project.
-   [x] My change requires a change to the Readme.md.
-   [x] I have updated the Readme.md accordingly.
-   [x] I have read the **CONTRIBUTING** document.

Pull requests should be thought of as a conversation. There will be some back and forth when trying to get code merged into this or any other project. With all but the simplest changes you can and should expect that the maintainers of the project will request changes to your code. Please be aware of that and check in after you open your PR in order to get your code merged in cleanly.

Thanks!

### CODE REVIEW

**Comment by jekuer** [comment]
This is really interesting! Thanks a lot. I will need some days to check it, but definitely will soon.

**Comment by jekuer** [comment]
@chadoh , went through it.
Could you resolve the conflicts with the current branch? This would be awesome.
I would then merge it to some dev branch first, and work on some smaller issues regarding styling and keyboard behavior - this is somehow not ideal now.
+ some more testing. But hopefully can merge it into main soon after that :)

**Comment by chadoh** [comment]
Glad to hear you had some time and you're liking the direction! I rebased with latest `main` and force-pushed.

**Comment by jekuer** [comment]
@chadoh , now live with v1.7.0
Thanks a lot again. Added a link to your profile to the readme - hope that's ok.

**Comment by chadoh** [comment]
Wonderful, thanks for working to merge it so quickly! And for adding me to the README ☺️

**Pull request merged**
